x-common-dns: &common-dns
  dns: 10.0.0.254
  dns_search: ${LC_COMPOSE_CLUSTER}.local
  dns_opt: [ 'ndots:1' ]
x-common-network: &common-network
  networks:
    - common
x-common-restart: &common-restart
  restart: on-failure
x-graceful-stop: &graceful-stop
  stop_grace_period: 1m
  stop_signal: SIGINT
x-common-logging: &common-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

services:
  bot:
    image: ${LC_COMPOSE_IMAGE}:${LC_COMPOSE_IMAGE_TAG}
    environment:
      - BOT_TOKEN=${LC_COMPOSE_BOT_TOKEN}
      - OAUTH_TOKEN=${LC_COMPOSE_OAUTH_TOKEN}
    <<: [*common-logging, *common-network, *common-dns, *common-restart, *graceful-stop]

networks:
  common:
    external: ${LC_COMPOSE_NETWORK_EXTERNAL:-false}
    name: "${LC_COMPOSE_NETWORK_ID:-bridge-lan}"
